### ISSUE TITLE
Geração automática de ticket para telefonista deve permitir que o telefonista o feche

### ISSUE THREAD

**Issue by aszasz** [protocubo/sapo#29]
@lehonma: verificar que o ticket gerado para conferência telefônica permita que o telefonista o feche (seja emitido do telefonista para o telefonista?)

**Comment by jonasmalacofilho** [comment]
Usuários com privilégios de `PPhoneOperator` podem fechar todos os tickets que tenham como recipiente seu grupo ([implementação](https://github.com/jonasmalacofilho/sapood/blob/9df25addc097717762ea62d51001bd966bf508eb/src/sapo/route/TicketRoutes.hx#L222)).  Assim, não importa muito quem escreveu o ticket; podemos criar um usuário "Sorteador@Central Telefônica" para ser o autor destes tickets.

@lehonma: como os tickets automáticos são criados atualmente?

**Comment by lehonma** [comment]
Eu deixei uma variável aberta para o usuário chama "sysAuthor" 
Linha 14, sync.CTicket (preciso adicionar este usuário)

**Comment by lehonma** [comment]
De resto, quanto ao teste o usuário Judite não pode fechar todos os tickets que estão lá, porque dos 3 que ele consegue ver apenas 1 é destinado ao grupo (o resto é destinado ao usuário, logo somente o destinatário pode fechá-lo)

**Comment by jonasmalacofilho** [comment]
O autor é mesmo configurável em [`sysAuthor`](https://github.com/jonasmalacofilho/sapood/blob/b92ae31ef83db8bea038b81ab5ea484bffaf5222/src/sync/CTicket.hx#L14), mas precisamos também configurar o destinatário.

Além disso, acho que os dois (autor e destinatário) devem ser passados em variáveis de ambiente; algo como `user:#${id}` ou `user:${email}` para o autor e `group:${id}` para o destinatário.

Também são necessárias verificações em runtime de que o autor é um _usuário_ de grupo com privilégios de `PSuperuser` e de que o destinatário é um _grupo_ com privilégio de `PPhoneOperator`.
