### ISSUE TITLE
Pagamentos: Incluir número total de selecionadas, eventualmente count na aplicação do filtro

### ISSUE THREAD

**Issue by aszasz** [protocubo/sapo#35]
Atualmente não há mensagem de erro específica se não há entrevistas selecionadas: vai para o sapo 500 depois da referência ao comprovante ser entrada

Acho que precisamos de usar um count aqui, tanto para o filtro, tanto quanto para informar o número de pesquisas selecionadas no modal "pagar selecionadas" e/ou enquanto elas estão sendo selecionadas.

**Comment by jonasmalacofilho** [comment]
Yeap, melhor a UI não permitir o pagamento de 0 entrevistas.

Reportar (provavelmente no modal) quantas pesquisas estão selecionadas me parece bom também.
