### ISSUE TITLE
Pagamentos: exportar resumo de recibos?

### ISSUE THREAD

**Issue by aszasz** [protocubo/sapo#36]
Acho que deveríamos incluir em pagamentos um botão que gerasse e exportasse uma tabela com uma linha por recibo, contendo: 
- referência de pagamento
- data
- quantas pesquisas foram pagas por ele.

**Comment by jonasmalacofilho** [comment]
Gostaria de ouvir a necessidade da Lorely(Comtacti) para avaliar o que fazer aqui.

**Comment by craice** [comment]
**INTERFACE PAGAMENTO**
- [ ] no Filtro PAGA, adicionar "Todas";
- [ ] no Filtro PAGA, colocar como padrão "Todas";
- [ ] no Filtro STATUS, colocar como padrão "Todas;
- [ ] adicionar Filtro DATA, que filtrará os resultados até a data selecionada;

**INTERFACE EXPORTAR**
- [ ] exportar .csv com a contagem de pesquisas a pagar por pesquisador por Ref. de Pagto.

**Comment by jonasmalacofilho** [comment]
Para o filtro de data, você pensou num date picker?
